///////////////////////////////////////////////////////////
//  Bouteille.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      06-févr.-2025 09:57:42
//  Original author: LLissandre
///////////////////////////////////////////////////////////




namespace Solution1 {
	public class Bouteille {

		private float contenanceEnLitre;
		private float contenuEnLitre;
		private bool estOuverte;



		~Bouteille(){

		}

		public virtual void Dispose(){

		}

		public Bouteille(){

		}

		/// 
		/// <param name="contenanceEnLitre"></param>
		/// <param name="contenuEnLitre"></param>
		/// <param name="ouverte"></param>
		public Bouteille(float contenanceEnLitre, float contenuEnLitre, bool ouverte){

		}

		/// 
		/// <param name="bouteilleACopier"></param>
		public Bouteille(Bouteille bouteilleACopier){

		}

		public bool Ouvrir(){

			return false;
		}

		public bool Fermer(){

			return false;
		}

		public bool Vider(){

			return false;
		}

		/// 
		/// <param name="quantiteEnLitre"></param>
		public bool Vider(float quantiteEnLitre){

			return false;
		}

		public bool Remplir(){

			return false;
		}

		/// 
		/// <param name="quantiteEnLitre"></param>
		public bool Remplir(float quantiteEnLitre){

			return false;
		}

	}//end Bouteille

}//end namespace Solution1