--
-- OAI - Création des table de la base de données
--
CREATE DATABASE IF NOT EXISTS PAPYRUS; 
USE PAPYRUS;

drop table if exists ARTICLE;
drop table if exists CATEGORIE;
drop table if exists FOURNISSEUR;
drop table if exists TARIF;
drop table if exists LIGNE;
drop table if exists COMMANDE;
drop table if exists REPRESENTANT;

create table CATEGORIE(
	CODCAT VARCHAR(3),
	LIBCAT VARCHAR(30),
   constraint CATEGORIE_PK primary key(CODCAT)
) ENGINE=InnoDB;

create table ARTICLE(
	REFART VARCHAR(5),
	DESART VARCHAR(40),
	QTEART INT(4),
	SALART INT(4),
	CODCAT VARCHAR(3),
   constraint ARTICLE_PK primary key(REFART),
   constraint ARTICLE_CAT_FK foreign key(CODCAT) references CATEGORIE(CODCAT)
) engine = InnoDB; 

CREATE TABLE FOURNISSEUR(
   NUMFOUR VARCHAR(5),
   NOMFOUR VARCHAR(30),
   TELFOUR VARCHAR(10),
   ADRFOUR VARCHAR(50),
   CONSTRAINT FOURNISSEUR_PK PRIMARY KEY(NUMFOUR)
) ENGINE=InnoDB;

CREATE TABLE REPRESENTANT(
   NUMREP VARCHAR(5),
   NOMREP VARCHAR(30),
   TELREP VARCHAR(10),
   NUMFOUR VARCHAR(5),
   CONSTRAINT REPRESENTANT_PK PRIMARY KEY(NUMREP),
   constraint REPRESENTANT_FOURNISSEUR_FK foreign key(NUMFOUR) references FOURNISSEUR(NUMFOUR)
) ENGINE=InnoDB;

CREATE TABLE TARIF(
   PRUTAR DECIMAL(3,2),
   INQTAR VARCHAR(1),
   REFART VARCHAR(5),
   NUMFOUR VARCHAR(5),
   constraint TARIF_PK primary key(REFART,NUMFOUR),
   constraint TARIF_ARTICLE_FK foreign key(REFART) references ARTICLE(REFART),
   constraint TARIF_FOURNISSEUR_FK foreign key(NUMFOUR) references FOURNISSEUR(NUMFOUR)
) ENGINE=InnoDB;

CREATE TABLE COMMANDE(
	NUMCOM INT(5),
	DATCOM DATE,
	TOTCOM DECIMAL(5,3),
	NUMFOUR VARCHAR(5),
   CONSTRAINT COMMANDE_PK PRIMARY KEY(NUMCOM),
   constraint COMMANDE_FOURNISSEUR_FK foreign key(NUMFOUR) references FOURNISSEUR(NUMFOUR)
) ENGINE=InnoDB;

CREATE TABLE LIGNE(
	QTELIG INT(2),
	REFART VARCHAR(5),
	NUMCOM INT(5),
   constraint LIGNE_ARTICLE_FK foreign key(REFART) references ARTICLE(REFART),
   constraint LIGNE_COMMANDE_FK foreign key(NUMCOM) references COMMANDE(NUMCOM)
) ENGINE=InnoDB;


