///////////////////////////////////////////////////////////
//  Chenille.cs
//  Implementation of the Class Chenille
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:35:45
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageInsecte.PackageLepidoptere.Solution2;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public class Chenille : StadeDEvolution {

		public Chenille(){

		}

		~Chenille(){

		}

		public override void Dispose(){

		}

		public override StadeDEvolution SeMetamorphoser(){

			return null;
		}

		public override void SeDeplacer(){

		}

	}//end Chenille

}//end namespace Solution2