///////////////////////////////////////////////////////////
//  Chrysalide.cs
//  Implementation of the Class Chrysalide
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:35:54
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageInsecte.PackageLepidoptere.Solution2;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public class Chrysalide : StadeDEvolution {

		public Chrysalide(){

		}

		~Chrysalide(){

		}

		public override void Dispose(){

		}

		public override StadeDEvolution SeMetamorphoser(){

			return null;
		}

		public override void SeDeplacer(){

		}

	}//end Chrysalide

}//end namespace Solution2