///////////////////////////////////////////////////////////
//  Lepidoptere.cs
//  Implementation of the Class Lepidoptere
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:32:59
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageInsecte.PackageLepidoptere.Solution2;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public class Lepidoptere {

		private string espece;
		private StadeDEvolution sonStadeCourant;

		public Lepidoptere(){

		}

		~Lepidoptere(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="espece"></param>
		public Lepidoptere(string espece){

		}

		public void SeMetamorphoser(){

		}

		public void SeDeplacer(){

		}

	}//end Lepidoptere

}//end namespace Solution2