///////////////////////////////////////////////////////////
//  Objet.cs
//  Implementation of the Class Objet
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:33:22
//  Original author: LLissandre
///////////////////////////////////////////////////////////




namespace PackageObject {
	public class Objet {

		public Objet(){

		}

		~Objet(){

		}

		public virtual void Dispose(){

		}

	}//end Objet

}//end namespace PackageObject