///////////////////////////////////////////////////////////
//  Oeuf.cs
//  Implementation of the Class Oeuf
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:35:06
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageInsecte.PackageLepidoptere.Solution2;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public class Oeuf : StadeDEvolution {

		public Oeuf(){

		}

		~Oeuf(){

		}

		public override void Dispose(){

		}

		public StadeDEvolution SeMetamorphoser(){

			return null;
		}

		public void SeDeplacer(){

		}

	}//end Oeuf

}//end namespace Solution2