///////////////////////////////////////////////////////////
//  Papillon.cs
//  Implementation of the Class Papillon
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:36:07
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageObject;
using PackageInsecte.PackageLepidoptere.Solution2;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public class Papillon : StadeDEvolution {

		private Int32 nbAiles;

		public Papillon(){

		}

		~Papillon(){

		}

		public override void Dispose(){

		}

		public override StadeDEvolution SeMetamorphoser(){

			return null;
		}

		public override void SeDeplacer(){

		}

	}//end Papillon

}//end namespace Solution2