///////////////////////////////////////////////////////////
//  StadeDEvolution.cs
//  Implementation of the Class StadeDEvolution
//  Generated by Enterprise Architect
//  Created on:      21-févr.-2025 08:33:11
//  Original author: LLissandre
///////////////////////////////////////////////////////////




using PackageObject;
namespace PackageInsecte.PackageLepidoptere.Solution2 {
	public abstract class StadeDEvolution : Objet {

		public StadeDEvolution(){

		}

		~StadeDEvolution(){

		}

		public override void Dispose(){

		}

		public abstract StadeDEvolution SeMetamorphoser();

		public abstract void SeDeplacer();

	}//end StadeDEvolution

}//end namespace Solution2