/*
Création de la base de données
Sous-langage : DDL /LDD
Data Definition Language
Langage de définition des données

Principales instructions :
CREATE = Créer une structure (DATABASE, TABLE, VIEW, PROCEDURE, TRIGGER, FUNCTION)
ALTER =  Modifier une structure existante
DROP = Supprimer une structure existante
*/

/* SUPPRIMER LA BASE DE DONNÉES SI ELLE EXISTE */
DROP DATABASE IF EXISTS tp2;

/* CRÉER UNE BASE DE DONNÉES NOMMÉE "videos" */
-- CREATE DATABASE videos;
CREATE DATABASE IF NOT EXISTS tp2;

/* SÉLECTIONNER/UTILISER LA BASE DE DONNÉES CRÉÉE */
USE tp2;

-- Les requêtes qui suivent utiliseront
-- la base de données sélectionnée ci-dessus

CREATE TABLE AVION(
	AV TINYINT UNSIGNED  PRIMARY KEY AUTO_INCREMENT,
	AVMARQ VARCHAR(20) NOT NULL,
	AVTYPE VARCHAR(20) NOT NULL,
	CAP SMALLINT UNSIGNED NOT NULL,
	LOC VARCHAR(20) NOT NULL
);

CREATE TABLE PILOTE(
   PIL TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   PILNOM VARCHAR(20) NOT NULL,
   ADR VARCHAR(20) NOT NULL
);

CREATE TABLE VOL(
   VOL CHAR(5) PRIMARY KEY,
   AV TINYINT UNSIGNED,
   PIL TINYINT UNSIGNED,
   VD VARCHAR(20) NOT NULL,
   VA VARCHAR(20) NOT NULL,
   HD TINYINT UNSIGNED NOT NULL,
   HA TINYINT UNSIGNED NOT NULL
);

ALTER TABLE VOL ADD CONSTRAINT FK_VOL_AVION FOREIGN KEY (AV) REFERENCES AVION(AV);
ALTER TABLE VOL ADD CONSTRAINT FK_VOL_PILOTE FOREIGN KEY (PIL) REFERENCES PILOTE(PIL);
ALTER TABLE AVION AUTO_INCREMENT = 100;