///////////////////////////////////////////////////////////
//  Bouteille.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      06-févr.-2025 15:36:59
//  Original author: LLissandre
///////////////////////////////////////////////////////////

namespace Solution1
{
    public class Bouteille
    {
        private float _contenanceEnLitre;
        private float _contenuEnLitre;
        private bool _estOuverte;

        //constructeurs

        //constructeur par defaut
        public Bouteille()
        {
            this._contenanceEnLitre = 1;
            this._contenuEnLitre = 1;
            this._estOuverte = false;
        }

        /// Constructeur classique
        /// <param name="contenanceEnLitre"></param>
        /// <param name="contenuEnLitre"></param>
        /// <param name="estOuverte"></param>
        public Bouteille(float contenanceEnLitre, float contenuEnLitre, bool estOuverte)
        {
            this._contenanceEnLitre = contenanceEnLitre;
            this._contenanceEnLitre = contenuEnLitre;
            this._estOuverte = estOuverte;
        }

        /// Constructeur par clonage
        /// <param name="bouteilleACopier"></param>
        public Bouteille(Bouteille bouteilleACopier)
        {
            this._contenanceEnLitre = bouteilleACopier._contenanceEnLitre;
            this._contenuEnLitre = bouteilleACopier._contenuEnLitre;
            this._estOuverte = bouteilleACopier._estOuverte;
        }

        public virtual void Dispose()
        {

        }

        public bool Ouvrir()
        {

            return false;
        }

        public bool Fermer()
        {

            return false;
        }

        public bool Vider()
        {

            return false;
        }

        /// 
        /// <param name="quantiteEnLitre"></param>
        public bool Vider(float quantiteEnLitre)
        {

            return false;
        }

        public bool Remplir()
        {

            return false;
        }

        /// 
        /// <param name="quantiteEnLitre"></param>
        public bool Remplir(float quantiteEnLitre)
        {

            return false;
        }

    }//end Bouteille

}//end namespace Solution1